version: "3.8"

services:
  bot:
    build: .
    container_name: urltovideo-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
      - ./cache:/app/cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
